apiVersion: v1
kind: Status
metadata:
  name: flux-plunger
  namespace: cozy-fluxcd
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "flux-plunger":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
