apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "1779313872"
  labels:
    cozystack.io/package: cozystack.keycloak-operator
  name: keycloak-operator
  namespace: cozy-keycloak
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-keycloak-operator-default-keycloak-operator
    namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: cilium-networkpolicy
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: keycloak
    namespace: cozy-keycloak
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 30s
    timeout: 10m0s
  interval: 5m0s
  maxHistory: 5
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 30s
    timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: cozystack-values
