apiVersion: v1
kind: Status
metadata:
  name: keycloak-operator
  namespace: cozy-keycloak
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "keycloak-operator":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
