apiVersion: v1
kind: Status
metadata:
  name: reloader
  namespace: cozy-reloader
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "reloader":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
