apiVersion: v1
kind: Status
metadata:
  name: prometheus-operator-crds
  namespace: cozy-victoria-metrics-operator
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "prometheus-operator-crds":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
