apiVersion: v1
kind: Status
metadata:
  name: rabbitmq-operator
  namespace: cozy-rabbitmq-operator
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "rabbitmq-operator":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
