apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: tenant-simonsfirsttenant
    meta.helm.sh/release-namespace: tenant-root
  labels:
    app.kubernetes.io/instance: tenant-simonsfirsttenant
    app.kubernetes.io/managed-by: Helm
    apps.cozystack.io/application.group: apps.cozystack.io
    apps.cozystack.io/application.kind: Info
    apps.cozystack.io/application.name: info
    helm.toolkit.fluxcd.io/name: tenant-simonsfirsttenant
    helm.toolkit.fluxcd.io/namespace: tenant-root
    internal.cozystack.io/tenantmodule: "true"
    sharding.fluxcd.io/key: tenants
  name: info
  namespace: tenant-simonsfirsttenant
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-info-application-default-info
    namespace: cozy-system
  install:
    remediation:
      retries: -1
  interval: 5m
  timeout: 10m
  upgrade:
    force: true
    remediation:
      retries: -1
  valuesFrom:
  - kind: Secret
    name: cozystack-values
