apiVersion: v1
kind: Status
metadata:
  name: vertical-pod-autoscaler-crds
  namespace: cozy-vertical-pod-autoscaler
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "vertical-pod-autoscaler-crds":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
