apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: monitoring-system
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/instance: monitoring-system
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: Monitoring
        apps.cozystack.io/application.name: monitoring
        helm.toolkit.fluxcd.io/name: monitoring-system
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: grafana-admin-password
    namespace: tenant-root
data:
    password: ENC[AES256_GCM,data:88e0OGnzLXynsFyHF1+qwHTWPnfxRAJ03OK8kwW8qy+YYOQ8YEhbOPqIupw=,iv:XwSAOq1GWRwgeOSraGFmwxRRbMhYlerKY6AxPJSUek4=,tag:o0wbXH2x/p5M1E7fDGRc3w==,type:str]
    user: ENC[AES256_GCM,data:ogNWYhCVDNE=,iv:qvuJjnt3rqA2YuOpDfP4EUAPx2uXHbd1GLKc/Pkdwow=,tag:6ohZNKI8ZGoBmKUwA5aNTw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZktmK2NYYW1mYVVCRzhD
            Y2NoR2VEZkZyUEtzWndRT1IraUk3cHh0dHprCmordnVtS3pRbWJMYndVYm9QYlNJ
            QjNWcWluQ1BNUDlZN2VDUDBON2xTbzgKLS0tIGlxSnZyMzdKRWlET2FVM2pSNFJ3
            Z2dac3VHbjUzRHdDR0h2ckVBdDM5Q00KXNuQq+4+Q/5WwKaXYr15BuFC7A5gGg0H
            ITZdzMWJ6dKEdmrPrLtn9dVJGkcRjuCPGIdkX6+LfBxeVAp+ezhSWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T05:54:20Z"
    mac: ENC[AES256_GCM,data:PH3fWpEbcHFt0K+GcitihEe99zcSQ85EzvfT3aVJmsYhWHZOpp4ekE4LZ0y634LvYJ05JRyoUYQC2cmyjf/Dmv83MOg6TLSjAtw4uwD3lQsaZ2HVX3PwmFuV2V7YLFwSjVY/ucad/VmNjMOYnPqTvjOD5qvWnIk4P7XYJX1ZdNM=,iv:qDUsYj6GO2e4dcU/52LK8Kt2aEyZvAj4p/8vucfLKec=,tag:tGVF4v9VcnSqMohWfUk4gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
