apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: monitoring-system
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/instance: monitoring-system
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: Monitoring
        apps.cozystack.io/application.name: monitoring
        helm.toolkit.fluxcd.io/name: monitoring-system
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: grafana-admin-password
    namespace: tenant-root
data:
    password: ENC[AES256_GCM,data:XuTPKM9/hGePuddlcwd/aybRV3HCfQ3v26sGaS2ySCS4u2hRV7lJe6Q2hAk=,iv:NTjH9igxNkR+ymP4OPfDfP/CJY2pf9IPjlSJlhmgvD8=,tag:Il6Ct5o1pX7xMSZ8X4SJwg==,type:str]
    user: ENC[AES256_GCM,data:nbcVJkbTNtk=,iv:EYWXuffQvCxkjXnd7Sh3u9H6+/zf0hkLD8MSTsS3+9k=,tag:Vj+OySYqIqJjmd50vEY0BQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaGVBTXpXdEFnb0xPNzYz
            eldtWlNKK3JvL29ZNEliRmd4ZXU4Tkd1Y2hFCnVrWmxEak9pUVkzK1NoS3JQL1E0
            cm1NTUd0K0Nabkp5akFMZWg5bU91S00KLS0tIE9XeFplVVhZNnJsRW9ac2YraDVG
            UlFYTlBDZU9ucDRBS01YRUJUOUJZMFUKnq83TXmW+BQhrxy83AWj8b6cH5B6Y10i
            DYJnz4G8pBtEGZcsB34YS/oS04ZYfFsQfjZ2RU1aBj3v6ctThvQE1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T06:22:23Z"
    mac: ENC[AES256_GCM,data:IsXwVTUPdL5kK4DX5kfTuR4DjRL+hwJ6Gd6NR9GXy1mDB0iIrjn5zwmxu5tAcEipLwQGKJbOadjM1GaShPqglqoaQaYy9JOrQu/YzTjtLsHwdcQiuB5cljWMXF9A4NzGZD8KKUp/gSAZdj8elTiYIUQkPX5xK1D3bB2QPya2HlQ=,iv:FlDYJDr4wEJm9wl+F5P3/oK0UfMBTFtOQj0PBjs5kNQ=,tag:KgIU5gdWiv+RJs/Wpc8qRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
