apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: monitoring-system
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/instance: monitoring-system
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: Monitoring
        apps.cozystack.io/application.name: monitoring
        helm.toolkit.fluxcd.io/name: monitoring-system
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: grafana-admin-password
    namespace: tenant-root
data:
    password: ENC[AES256_GCM,data:Cm+798vIT3eQXTbZqxlH1C537n4v6JxVRGzZzhrP913hN/nOXVizfgaXV6c=,iv:vL+DZPR99VQufG6N6re6N4BGFpeFKF7S2YpFZJ15Vx8=,tag:x0H6A6pP/8qKKYLdoIHq0w==,type:str]
    user: ENC[AES256_GCM,data:Fi432MiHpp0=,iv:8Eh235MRCNVsvYsxbG86RvsSDLCl2e1FlKqPPNUNx8o=,tag:pW8UGNf2eFHoumci2JVeBA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVi9Kd2VnQW9Bd3pJbTIv
            MU94d2pITjFaSUJ4bytsSzNCakgwdGMvTVNvCjZFZ1E1NWNkV1FiRGFpamF2akNr
            djh3RTkyNXIybHJvbnNQayswUFlkMFkKLS0tIEErR3Q0a3FPWUxsdHU3UU1wa21R
            UU1IMjczdWNaRWl1dWE4dkNXUWJ2cHcKBz2sfGpJsZW6rwTA0WZ5q6nVeryUXyIH
            wDCfv6Jy7qJOmNufqQ+4+on6KVpyPOHhMvfgwuaO1hPjOmlXD/mrNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T05:58:38Z"
    mac: ENC[AES256_GCM,data:HhMRjSoQtpNsjlPXBY3YoQ08nqpLu/xdCvZLomhelJKFmTNyDYLtvXPYxi0Hjpm78z2zZmg9beBjCpLXIFqtTzX2lJ84+JA4ziAmvXXexZywlS6sekv1Zlz/T+x9C7hg5UxdEKsGUN/t3PKcKtE2H+b32gOrwn9n86VZHLcJAOE=,iv:A4eq27KZW6ePoHbvbO/0Q7E/mdHznV8v0nLEgLoU4uw=,tag:O6F4+ZMaX1/EEFQT94OTSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
