apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: info
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: Info
        apps.cozystack.io/application.name: info
        helm.toolkit.fluxcd.io/name: info
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: kubeconfig-tenant-root
    namespace: tenant-root
data:
    kubeconfig: ENC[AES256_GCM,data:1jcGg7rxz5bIE7KCiRueCjyfrCBE2z24wzOu2KZiqXtKPBfpC8MKgz3uMkRpWOy52rnJ7sYPuEKcW8YZYViCbp5CU0pdDyJfCxEvnhNzfSFzlQEiGadDp/8pYpOEMd3qJZbzSRW0VveDJnbxf80PeIy16ovAd2zzf2SeS3Y7V1yXxtnCr7LdRFuT7QxNo+iTTIn1D8HiSGSz5L5/MwTIKxFh7Yz5QI8bRkWKfL6WWHmWOPnwkjxNcuDx3/YzDLsLhXNX4cZgPXv1jRJShgpMWnlgWXibbEYWNCF7qafp1Ue5IX50IKmTmGpcBWpY99VkFfHfGtixfe17JSaIxgeOUa3pzm1Hg/Vi2f2IJO2V4cW2xeyN73PxLeZ4FRWTUiGL/Wbr+IaUb8L0VcccEHgSq8RG+HR/ncrqh1Vrk6nINLd4gQ4Y8HClVjLldW+WnkdF2kLgiszqamQlqrlJ92fW6mgOQ0YJH3OfoCT1hreQvTjjYsw9A1gQZNib8TEwIgnCpiPMvcE42+zl2z9rUSd9NfBs6JtYuOfmVQcWQnJn2s3qydzH1hLRtMvKbivW2dARPqWiEW7pMX4krTw5PrhLNjmySvmvLy/4LZhKKBxKt+e110VI9/jAbTNcNF4gwegFpMR3esmarZnwYwEH4hA43kyGFJs2qysYQJjXhqxzF/7uNmwi/0dvci0vMxmxcakC5ukr08vs+XXf26+lLRSBVAWp0gw8rzZDal/CZ0fZgTEAF7PSQVSIVnCasySIRfbpKwlEzV3g5T3PaJ7hX9JeakiniIOTut0x5fH7XVUaYOeYMtks/7+5oF2nIXKwTGQqxavFDSVRHlJMinlUDTMYEsnfdG2dttGuhMVBp/RQohjWBmEcFMdkM6YvXejvDL8uwvN4/Jl+AkDoIbShKYerWbnlKlTmnCCMv7OV3U5uYDym3NIcDcB2bl3Rowyxp02dMbMo2AZ+QNLnZlDhCkwicdr6MRxUb2f9bGEP1tpPvMHl6DGkxh9fVNYXxJi5EalR1kAcvv8HD3d8Aq2MtSe/JNKP3cyK3rWOmCpzMS0a8rkacE2Nzly3dSwPTlPE9r7VtZUzPNb71oApVmL/6JE4flnvqsGtP9xvzs83ON+PnidvQjFEmndhdnm7VexMvKi+d9HsTKjZnfn0fx+7RNVeKSBG7qmL0w1OJoKvmvBrYUz3kbNdXg4lt5MIhZBYBi0ds/JIyr9r9h8aArLYSkr7irIGJNO3DYNLYpOq3aOAfW3GZWx5vD0QspBmaFZoo/TEzp4t/uebAka7KyzTFXKSW+lbuSB7LxtQnykxVtvCDvvOX4rqmYgd6rlgmPUj+QqZm5HDbheDwGtuGh7eLsZP7V93QYJvfsK6dVTgHOOPhbGwCIHS+sM49wtWrLo0qzlnjvxHXfhCeY7Bi7VQWUAW/4/oHAtBa1GuVYYP0MUAZSMPNUdEdudo6iW10KIfY6rdlZ3uWmWtbpCmYOSWLm/MPzoQ/cop57Rryfp5d+ql6lp0VELtas7aglf+YXumPShnh4K6fLy+/t9FE6g9Ec8Oc2wZk5rv+8dR2F6p5MlwXYfhBdwk88ARqsmdMvbW8fEa8mjZrAjWC5+h7CVv8yyGguswD4HKx1tx8IAhcxXcWw7h1sJbzwSDSEx1UPhRR2NtHj3KHBwO/LwVbffeKpE3QDFsxp+j925RLeWKHCxNMTw9Nn3IV5mXnZgGumiUwXyzoKOGh7no6tP7pSgOl327bU9tOQzSQQ6gY7quvcnbmy5IUgqhKZ5Wqcn4ul8C65kCYJFE9FRs25tctrFtvmBYNm7T8lHlpUBSwRpMWp7UwyktzSJCG8FMMVLqKcDKOAvNuo7VsaxTZoi75v1vyndLLPOz5edW6VdvEBpLoIRcY64YskVZHENKC+gVyxP4imR5Vc1gYnUSAak4BK0U4LD2g87CEkzedtX1R75R99ns8o0KHn3Ul0J4TKFI/kgycDR5u3HtyIJtQRLic36Ud3yES48zXDAUhQJDZWiGUS8qX9hTpndLRR72C4/x121U4keETMeRyaC3F8u+aNHoVq5OKuedaCO7ucyisNpI61SqZtgpYjqw1ra0vvCz1oGT2vHinZr0tOC9e14O5h/Js0hTrdC3OQAYeSopxjDmQvEZbVddeWdcs47ZfM9hTIoN3VA2pAXML/pyOZEbphWW2zcCDHMijPmsUWpPQd/OF0y8QYe0LGSRCIltayKDiqFk+kuUHnVbs+f457A8dytPx1qsqLjibloNmDxsC0kSjzpgPck0kNtPGnAo8Sue43re9MfnRNK9/yYQMZbQBfJhN0IgL0VSQ+XnZcruj9GwCtcoylpXYGLwLV/FOF7BVzG0xPMqiCyTYoCBmBogadJW70/RRU83mcXBX8C84SpEHw==,iv:5Yqp6JdLLAuJcMICFs83fiaMNFrdid5BsTdAU4Ju0YI=,tag:aQHbhOaCV0Ejc8wZd/4bSw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubkpHZXRETUprVjl0b05h
            bkNzUHF0YVUvTjVJM3ZQd05kM0s5MVhBNWdjCjRIYlFGNDNyVndDa080a0l0R1dD
            ZWRoL0craGtGazVjYk1OZE4xTDg5MlUKLS0tIHJXTWM4bjN2akVaU0htSFhaa1Mv
            Ymd1STNnMEk1UllBaFJYRC9SUHJESUUKTKCXx6kxtnyCFR6ulsTG1659+42HmyZk
            Zf6fbGhZdYNZsIsYJpKPN9NWU9w763DVy5G7pP4pb6ec8giD1sXKtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T06:22:23Z"
    mac: ENC[AES256_GCM,data:ro+qBlyi/1S7TV5DEXloNB/1gCqT3H70UdW1hpM2H5u3ifDfbwg/0xQO1BDF4uSrIERfNdKZxJdwDm91CCXnB7zqHbxoTDBCUmafWgFO/l0Vg1AIoxsFjvdDXbEQvQil6bDFxXdWAgxCrjNIPCSzT0Hg1EXAyrUNrtvupKMte18=,iv:jDMUf/8dJmMMTXc0OPxRhTLRPjevMhEvnAblH0jpSrE=,tag:xuizI6oC1dl5zaXpfY7CIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
