apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: info
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: Info
        apps.cozystack.io/application.name: info
        helm.toolkit.fluxcd.io/name: info
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: kubeconfig-tenant-root
    namespace: tenant-root
data:
    kubeconfig: ENC[AES256_GCM,data:yf2p1LDlAobXYJnAT+ogH70PCPJCHI8u50AV4o0zfWeM9QKhjhJ5BOwlDXthR4uSkJeOMfcCM7i/t4L6aEokxWxqKW1baqBLrnMofaZrjfspXIcfKbgkhnD6uMX/du5WRKPQHGe6nzKfp6BiLFI1Mfzq6NSVNJqSftlDPcOJ1rwCRUwzCDMvfM6pFNB+DapK/63bLCJmW0ld5nI73l6O7NSniBsphZpI7Rvz5XYa5RG8Wd4bo8cxljX8NmMKFicm9dUAKdvRwLMa8U/Ev1X+X0lSVi2eYFrtiY2Ad4G4sYqMKVLGRyGlIO4BDTTTeBcUNqxwssCBg6I4VKa+WP52o8jvDybtwfq93D32xl2tFAEEbnQk7I3F9f0jKvSdH1Vt/B1dfIZlkbSvVC6hR9m4Yd422mHZ8WrHl8c/Op3mX3Z8zSjvb9IZWYzjOsPKMpeJBxwtW2wL9eylP0PFZlKWo8/cE2+ZUAB592K0d1z40bIlOyzojxpGil2/T3KgpK95a+ammpVE8t/11gf0kF1S6IA5xP8/qLavRdyWT4c0WBh+g3gi9IrC9Ik9ZvJ9Ut4CMorEjaQ2/vR0LT/WIphd/yqKgqJQsUeOBLvj6AQthbVQLlxXcQ9JGkfDhYjV7beZy1sdEuIHk7x+yKkL3ulI9IW7yMwoPpvNb1AlC7EBI5m+xO5ULKpOKX4eH34RXmRvwtgRtWuZQSlnVpMUgLcmoS8uKj9dmud4LCWMaLhaPHsDMNA/LztBsE2yKMBf3KwNKdDH5e0a7yq/2JsZb4foc0X7aDLMRvwBs7ijqBxrcBCRjTkCdWHmWV8AHGIpj6EPDOMB2c00DwJK+dlCffjDbwNz+6xibPEGEIVDsDz2232sKhsUrEkUlGVnAA433R0Y7QrQ4+bJuLg85UXCxt8OPNKOoTguBxW7MSNbztFlRbj2W48wX9VyUC6+aCkLii/SgHeWqjFyh3Iy9XARmc34SmeNFtbHna3ArH6BtvC+ofOY9G5f0kqpEL1puGuyPJ8aowVCrIc5j3+s696zqCra7BgmbhqlEAFTzrCzWkkgqDxF92Asg073AtHkq3VSJgrIX+dZ9srixmFRyyw5f2fU5beWSjmzGMdiTBlg9wiS3psnriSDL+s+LUsPxihXb5wmyj53/ClbEP/xJ6XNxl793ceU1Xc5oPlgGQnlHnUB1P65aAon1ZNqNKagfGf94WS0CNchHUT6qj5EWY9ebrBevZDxwhtsGEXPnXnVcqDU8OPtwBJKrsgAM7BWevLuSg9OH2plDtQmDTIOJjzRZkD/ZlCxfydYLFYxg5+45NHOBPormsCV5vL0uA4hXNp+/Lq98WGu3UovvNWwIwp+UAwROc4yZZTMseF4CamUJhh+OxpaDU6uEumYyYEIXkG+3KmTzgy3aN+3Uyw7NzI76eODCAwlBxXpT/2aYx3Ag0alHX5kiRLidWsQ/skATbWAcA9XV6OLoE8x/OJXCA1dTtJj9AObR9jJxnUQI8rayfy+jQ5bmbcVjZKsnNLjjiVUQZNUwAKFIikIh+G0hjS4evMaVqAZr8C6BVINnQ6YSnO077xTwJsGge38VI6vG7vMJf+QrvZAYOqQyZAYUuk1muqYDIQy5YTqTjBuiKDBXVdmFDvnG8Kb6GDIaFSMGG2R+7RWXZTycOkStLY1mEwW9FVC3MnfvFSU2TUIoA1xA6oaQmyPvUIeW8BmVAbN/SxU06ERvmFI7Qa0pXJmL53I1eGzevTQhLzrUeWTTrK9G7aT7O7VqmTNc7C1wrdEq8y4eGbEMkKb9mo7Hk6WH6wcA/Ek9MPCd4W7sbJToOmsAe5iTNh1zn8i33UWCdcRFbTJQtly5keunTwJSFiUDtTGA+TCX/8r0t9+bsIp3dkzH9gqZpOrvmevSi0oKJpjYlJIcM5zy7cXtDt+u6P6Ef5DPpRxN8ivXOS3rJ5F4VhcZXeGMhaIRXqGFwKQQHO+MWpiRIEeg77xpbMgeZuGcmrGNSs7UrYZcrxN1Bgt2hcGose8UXrG2v/HGNdvG8YU4rp90k909h6BDvUPoodj/xR0bXiIi5wXdwWJHWUNvCaxwkt69yXhyNL41u3iCIYOjXmqAyH7Gxc/agoRlZPMbYc55+Jw28UazzSTI8t1Zo2ZXPLybbKjbRPTwoSypz2M9DIDiWIA1rul0cAhvV7R7uQmhg/iULyRhZkAe1zeimgbJ9CY5+CaLzY5EnuI6eIPzASbkA71NuZVu/zrjSvBC6tQTfd9q6NuoUTL+8OImq/CUrmuWtJ93nBVxMBGtMCtSUeUy/JoE+M9QqIqq/eZIujsD7bPHm3uyCwFBpPp08Bm6H2fLAsgaSrvaSFXzg6p8rOXT2TjU6JTU8GscQ4xKcNsCQVLfvgMtsd4ANwL5FRvLg==,iv:FeYdbxZBVLJfmPeRv7eq4Ovj4bf4/RHr9eVfHheD0SE=,tag:rcLVKFuEXPlTVljAqpRxXQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dnlidTBRejdMRDRDYzFB
            bFJ3WitPZ1I1SVFZOWJVWkdQcVJVSGRaSlFjCjluZXpLdCt0RndqRmtsVm5ETVFJ
            dTR1VWNaRnBTeWhuR0p3OVZ4UUVLQVkKLS0tIDJZT1ExWldsQ0xGclFRSXhGOVJB
            bzRwRlladWs0S2pXUkg3cktVd0JTazQKwGsUOUkAwrtoxqA67FIKTYt7eG3YyVGy
            LUq6xl6GrksPlGYLasdJMmMAp0uLczoPa0DOj3dIJONjzJIf2ZhWEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T16:14:15Z"
    mac: ENC[AES256_GCM,data:L1IO3a66oT7Nhdr8GDLxPbt+Ic1nVoFfiash5i3hhACYSwZpVXC5q0aBzREEfvENN0IKUXWPdkmpxIYXV7fBaf1Q/VDRxmXRIZ+pwhBo5f5e/26oBIyn+sU1PQ9d2x/MOO8pEKXt04aLI3wlayZuHq2smra60YRZxmc3npgvxas=,iv:srjWFIimgMKm+4HCkX5MlXg/lrMXoF5RztzPgw4jTRc=,tag:+D5lO484To8gGd3VgBmfSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
