apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: info
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: Info
        apps.cozystack.io/application.name: info
        helm.toolkit.fluxcd.io/name: info
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: kubeconfig-tenant-root
    namespace: tenant-root
data:
    kubeconfig: ENC[AES256_GCM,data:sSGVG96oQlPAH7EaXQrTovPwN7AJORrrr9Fmb9wJO2j2KRNcxejUooocCRsJQnlKTXkwiEIHHc3Bm1oZnftbmdTT7R0bCyiJHtshjZjZq/b/uC+XSlnv+0VS16bfa3BsIqUCGRsbEs/1pz25oAjOga6p3smEQxPbyJ6BWQAZjxic7UXvj78SrwDe6+sO12Bfw/1/8Acix7h8vTrB/KeB3RVkZsVWzoHepGtwStEaVMmlNVtRN0zH43b2ofYcZHJOfVDj7uHdE9U1q9NmkJ/7gvAR1F9CQgk9ooRESS1iUoxRdUPsqmtRXRdofHGzg5TPZeUQXReZc4Qo4KrJhslxkAiNoi7gKLiKj+FVOoaIbfz9w/+ooCCORhU6UNt4p7CyYOymsnpGC91AaydtGqt3rRyGBKtjsM83ypsH2U9cnyCl86swFschg+8yt+c/fv6mIA/AggfD2eSgPFLflp4EzbmxGwhMhSoVffh8112EnwrRuz7DB5IlpPcVRopJF/SvKXW5viJqAgSHJZJnFVrPPWwUC4wmGAb9V7gcttHzi06HAwwPTmLt6JoEgeUIt8wL2YQrETTVcoyXJoM1M7pnLi3O7+jdr4Swt2a43ilsdmLy0rpm5TwKCvnl0PhPne0yDE8IFJNuhbgHswFmr4uwpA+DiYTy4NXEV2hsj1ixp6nMVqq5GFzRiXNn9phNGAWVgFO2ithrKjwx18A7OtZ9mXKZcIAdSxoPh4qJQT7DybxsUXmTjq4uKJIBOJ69X+LCh0cWursW3uublcXjmqnpla3QLbVSw1Dg9aSgPZ4lBvojGJ4VQTcTntGJaFjXbGljiZXpiitDXsHQFSQ7LzExmM2qwTHL4q2pXme7MZ7SF6o4yEtZ0afC6lnuc8URy3Ri4/eIQEWcbz+ydPMRhJVNHOmV2XLoNWqjXeqw9uqOWoVowsaddVHVjTiuDRmNyCMI6t7Osl9wjSxNPX5tpSCW35icMowe9jfKTG1822lHsR6Z5LMKSJEPk1mG2eKRQjuyfJclRJio9XLPS8Yc2v8qnTZ+bDwfgRxIyk8A+b3WhckKR+XEL0Rb9wLxyMiZnq/NqYOp1b4p3ESFEg3b0f+0JdbMJ4kl/pR2HtB3mFyy6cgEf95iHutF2PhAI4OlvVrGr5nBo4pg8bfKkEq4WzH5wcsQKyMEutWplWhkYAuBE5Em4Mam4VkI24HHB5OxJNU+0RVsF+YCVwUcWpyIAUb/HNnhaPkOBNDgcTMaup5owG8r95wuu81UcZ/b/XAPtkL2qqDWMshsLHHKisSsMBYcyZplKdLQB/SFXG+3heMEytGMD8IvGnz/kaQHZXf5/llsFsMWwAebx1slZff9/2vPeVpxIV7RatC2rVht+3HIMsnc6Ci4shwWpTMcTeM9MTnQdDNUYhujHhoRu7BDWTL+iE64upklGbfHq3lQ2QrqXK0g+aXxqsqH6zZTk3pMx078JTjkjVALdv8dsLi0mRPLZUOHwgYu1FBDoAkDDQxi6p6C2nqctWO/XR9eN6QWVh+rusH1IAC2dCPrLKnK87cl2dCJb4ytij36/vGPiT81lXET4xlM4s0XUg3c8zbitoXkgGCH9uunEkg6nlveXrCMfm/02Sy06WHcqgcyuzCV83/xVfrzW4xRQuuSXL/TE0/IykHxM4THoKOaruZiNutq8VERHCw/ExUb3u3Vfy0pTRWGy/4zNg9nlua6bxFWMZsBYAXAFXQI119owz3iSMXg0xIAGWVL4Gm/q5GKEIXxBQFMkk5gh4sXo/F8G2IXMpcA+NYQMziybOVtOXcefnOpq0yKGBe+JlS7+S+6TRSle/4hEl2uEzzjqZZSRLufy32ieTtX+eC0pToKVkqo1X/uogqj8rsATaVQWYmsp2STJOsRxkdBmJsZL3ftZJd7N/HCJ18dGcyNeDPVvD/tPxfSF6ISAUDtGLGuqX2TZxHgx1nZx8065zvlwzwieTvDeoqpsI9zHwzC8EP2Ph8pEolP1d3M1sygDVrB+JLL6hn80C0jt6vGQioBT4mSZ7bOCoFJqARc1LBLa5hTUU2UvHVxh/7T90B2k0hu7BRIB6nHUCdqADHs9+oWteCBRaHk4spcSYGolJL3GSiwzB7QcCMxq8XElZhag5bNe6IInlShdBqhPrroonLnaO3s8DCDvO2JTCWid6OdkvBvfhqyrmd8kcC80XlCx/JLX1kuNbL0NJ54XVYgCC+oIKJFapGwZQnzXtKOt3iQObxmwPU2HbE6ii8X9AI1AyiNQgI2bYEvg98APgvH1YbL9Yj4y5MCmUpCPVToH2I7AY55NbDxX9wtO6KSYI3QGJ+kBOC+uk16Jclo/eXQy0a7ZIZts6oQ62oqzAYFdLvnTwotFX6DMWPl+X1WgyJ0r/z3Ly983Q==,iv:QgLJo0PMbwTd51yf0lns5RIEnWRZfm5NR6zgmGJ2SCg=,tag:591R74HYjMienJUXDY65rA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU0lOdU5neWtNUjJ4UnFK
            ZVREckVWS1NUa0lkNHJUa1IydkNlTnhtZ3hZClB1Q1RSVkFjaHFaWkFCSkJ5VC9G
            V0xjSG9EMEdHUUV2OHVUc1ZFQWJ3bU0KLS0tIDI1Tk5HcjA4aDVMNUlsQ1dHem85
            NlBzZktZbXFlemI3aEVaL2Z4RnRVL1UK2cJMBUCinVxo5TXjXSr6fF9V1uA7oMad
            Sc6+FKEDe4ykqIuVpC+koW5oA7ZZ0IRXGci04Ff8Bez+O2AcE+NofA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T05:54:20Z"
    mac: ENC[AES256_GCM,data:5+3g9/2F9v1kTu9n6yngssr8ZrfoHYFb8lB/8k2KPZD2WwTWFsv3TwZY8qyd9Cudiye+/3nLGGPYHaKwiF1c4DauWEzrUOmgnUWF8HLpd9rqBH3MMAjjsfnXF0396Ic+d9OvNmsxkJfzXIa8Wo5I/0zvIcDOVMoOH4pxVPwVJxI=,iv:O0AOuprxp29owedQ4es+DTIp+AAr0R8m6Cp3W8VbVec=,tag:qOgeoIEvwLUj1qOT/7suMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
