apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-my-first-again
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: my-first-again
        helm.toolkit.fluxcd.io/name: nats-my-first-again
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-my-first-again-credentials
    namespace: tenant-root
data:
    simon: ENC[AES256_GCM,data:0/xzflZus2OYAp7T,iv:MHPkjEq1CQ/RsznazrteOaurpY3+T/bMXJJnSSM0Jo4=,tag:Za8JNCWRkh1nrOVSxNmIyA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdlFERHYwb2tCa05Od09M
            YzdVWUFlVjIyWFluN1JWSUUrMzRTZXprblJBCkQ5Tk96OVVPSytabFJkRlBSYmtF
            NzhHSlgzTUU5NW5rMC9UWjk5dnh5L2cKLS0tIGJwYjRLSGJvSnFEUk1jTWtnT0ht
            M3pBRFhMRWZkL0U5OWhLblRZZS9tNVEKtDzBz5a+9S82vHk2qGmDxCseT0dQUSxm
            ZN6YdJG5I3bPawDMHqyEnd/vxcFPutzCTJOXIlXyXxMr/mdHpL8qDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T20:57:13Z"
    mac: ENC[AES256_GCM,data:R+8fXGerkKteVDYrAcipPlJR2YflmyZYzgSGY0AGN0qYHSGzHL8Y+Kdqcc+AJUcZx3LGDBXDrbmCRQJ+SUItdC7RF7jQpEk+sTyKuLb+YnN7ZJEbFCU5brcfjSV5/OKGJF3lI8vxp/AWVMdGtyaAwY5/DYu1GY2jkSe7DXr+3Kg=,iv:6qjSz5DWacCNm+cUWYti8zhZvhErcI+lgQANKNsqAPA=,tag:yIs0D57XigC7qOMYBKFzZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
