apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-my-first-again
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: my-first-again
        helm.toolkit.fluxcd.io/name: nats-my-first-again
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-my-first-again-credentials
    namespace: tenant-root
data:
    simon: ENC[AES256_GCM,data:WNTeO9EQ6uBCVGnk,iv:xSVbH2KUMm5rHrDNMItEXOU2idXCimQI6C2LYeS9dns=,tag:6e1hDM7lwaqazWZmMkxb5Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aVMxZnFRY2pxekhKK2Zj
            SjBxaHlyWGVEMGd4Z2R3eFZLdVV1SlN3b0FZCldNRGIzVlp1T1JkbXhKQmlPaTZk
            S3hJbTcrejQ1QUpYd09sdmhOZlA4L2cKLS0tIGhpSUd5N2ZhSlQ1YUdhclo5K3lW
            Tk5LR0dXYlBYRklyM0M5MWxYalVKalkKTy5UF+LA07+Wd8lTCxiMQpy91Ceb/1hn
            eGE/TxZXG2xDyMwQhWRrfaj2hdmgCkhQx4R26zfV157cnJhekv9GIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T05:54:21Z"
    mac: ENC[AES256_GCM,data:TnEXC/dVNyjaHCKVLcohxnSso+nXqRbPiTGGjobVjBNJnmReanmzOVKW9JXsPH7gVob59YFRTGwjhKT4Flo/WAwxKsGTtHh+7eI1szVTwRQ9SiG75b1Ef2IGBuVCpKr2XynUFp/Q7lAf+WrfpuXoK9qZLKbLGPXmtWsV+mWQ6U4=,iv:WKqq8Hji7T4Infikb9CUjI4Lx2z8Z3NE2EN8p1Bz7KM=,tag:i/qhH9y1Jo7W9619AcRwVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
