apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-test123
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: test123
        helm.toolkit.fluxcd.io/name: nats-test123
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-test123-credentials
    namespace: tenant-root
data:
    23sdf: ENC[AES256_GCM,data:J2OE4g==,iv:eWYLJWPlc8kxy2LniRj6gWB9CNMk7XsIy4UAZ/yLu3s=,tag:+FudTPAZTAlfFcJmsNybLA==,type:str]
    s: ENC[AES256_GCM,data:5GPaOA==,iv:leLCBPPetI7PwH93lFq0avPF63/RgeHHUDqSmol/kA8=,tag:AcRqyQptCASq+CPGJxW3SA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVVhpWWE0dEUwS0hVU1U0
            UXNEMmNwSzRVUDdBcWpWSzh4N2U4MmFJTmdzCjdXdkJHY0N3eVpsMng2eFVRNnZ4
            TjIyMHVrTjU1MmJtOVlTZGZkdnJkak0KLS0tIHhkeTRyK2JNQm4xZ1FwMVlPTUhs
            NjBoTXNHSWo2aUI2VVNUQ3dtUjMwM28KiEQ0ltHUY0v02ipCjS4qufmEoV9iDyJj
            99UzN07XCn2U+xapefyf8bFDqQRGiRQlaMOG11ycIianSkmMBIccMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T12:49:24Z"
    mac: ENC[AES256_GCM,data:XC3lo0o/8nz1hyinDCp3lUMJRDUcU38fhJCDUnbgZqKmAcMmuQQ9Y8aH/v/JIqnkH9/s79r0OBKgMtpaBRk3zqPT15Vc5IzymxQmw/sOTSIs8J2vjvoPVDXDalIxzg64ckQN0h92vQHZpgRJ8pzJuhzPySkmkE2NhSsJVscUqS8=,iv:wgQg6EaV0Qgk1t6dq48CNVy+ToJS/HoIe31bzJQ8h8k=,tag:6iu5tloPr5MhaeecY17hzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
