apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-andmore2
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: andmore2
        helm.toolkit.fluxcd.io/name: nats-andmore2
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-andmore2-credentials
    namespace: tenant-root
data:
    siempie: ENC[AES256_GCM,data:xR4ZTyx4I29bJG1rxqgbtA==,iv:1PSugrwlSebNEW117b8iksOJdQEvBiD41Pq2dPjtdBk=,tag:j5BT8XAMp6K70YJCkSP6iw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aWdxUGlDZ1JneStiVnNE
            Q0NLbjQ4VXMwaGowUHVMOFRQZlQ2RVBDR24wCm1aanZGOHYzYjZWK3dEWlhrQ253
            cDlLdTQ2L2JIR1VqRDBPcUhFZlU2TWMKLS0tIG1sRldFSUM4dEtQWnhudlRQblVU
            VkdOMXdjZ25qS3Z4bkUzZVBpNGRTSGsKfBjPmDCcWh0085Oiv31pU6sC3lIX7guU
            iKdGM/yi9OqE6f/mE6PQo59Qr/3QqEIOgZM8BHuVcegilIddGVgH8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T05:54:20Z"
    mac: ENC[AES256_GCM,data:rY5ZkfVwc87sQqHemaeIkvLG60dVvDsgdVkxWriIgsaiCMXu10TZedYnR3NLykJtVcHwqKbf/1ew+8xI9j0yXadC8N0CGLII94rzZ08/dnGG/9LCv72gAYRe8sV1i383BLMa5cPsWIuVQ6YsWufAPvx2o2OA+Il6+t7Ee7mlzdk=,iv:XWTP3X8b3enlcWXFFzKKecig+Ewallozp9p+lUk1ExA=,tag:lpXuf4vyYqYh6WPzyK5LJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
