apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-my-first-again
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: my-first-again
        helm.toolkit.fluxcd.io/name: nats-my-first-again
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-my-first-again-credentials
    namespace: tenant-root
data:
    simon: ENC[AES256_GCM,data:mdxbS6ZEaPEq4gX5,iv:hebOX0Lk6UCb+9F+SKuMknn9vsBnH7sm8TTsuEy7U6U=,tag:ZNNWnlS2/HRFtUwEH0pZUw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TFlQVTRJU3dKeHMzQ2hr
            alVXUGExN3gyUFRkNDhMdXVxUDdkVWY4T3hBCnhWTjJCWTJUMUMvWVlldjh6VVcr
            UjNhWkdOWUtFUmVUQ2ZsL251MjZFcjQKLS0tIHlKalJMS1N2Vy9TOU9YbzRhbVBs
            d204YlFrS0ZxNkF6ejMzNm1zcWh5QncK7C2bSUacYIC0aRqBK3SRLsIpCmIDJCJV
            6JK/+/e44TtGTaP1vPTD/0v26yn3k9YX8DYSWQ2UvxoBVO8BQATJ4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T09:28:48Z"
    mac: ENC[AES256_GCM,data:WxobV+gp4RfLPjZruCm0Bq+eJsvngFo9MK2SzHT0mE5qpnPdJnEfhc+DML0zX8eY5lCEsenNDEDu7XtZSsho/KsfDgqfJKAfukvGuYg6bXFTjVNiHBBCKRJQes03Q7Z69Z9mZLZ2QH+wHtWPMaQ4JDxHzVg9NU347jKwIEgqzKM=,iv:+rhSMOy5hfltyl6UBNOuNX++frXp1kENc/9LkNEDtlw=,tag:dAi4qwDgzHFr8kC+P+Q2LA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
