apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-test123
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: test123
        helm.toolkit.fluxcd.io/name: nats-test123
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-test123-credentials
    namespace: tenant-root
data:
    23sdf: ENC[AES256_GCM,data:sUphuA==,iv:lpp2y6yCK38oXfJXa7NAMk7jMTkhdWcblYQNEZZ2Gvg=,tag:tz7LPSxvzyMTRpHY2nKLgA==,type:str]
    s: ENC[AES256_GCM,data:BIT+EA==,iv:jkfH6S7dw4QW4RavUh3fKAhd2gbKSejGpajH2Zfpn2E=,tag:/yX/6ZSD97TR8aZ++IqvKw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseEVyOFhXc0xBOFZaUis1
            dVFmb3ZnNGdXYTcxM3lsYS9qb3RrN2lsV1V3CkdYQmgzN0cwOWNRNGpXQ095eTIz
            ei9NdXNmRVBtZlFyUmlDejVBdzR0V2sKLS0tIDNIQTRWM25FdW5teWFsdGk0OHN0
            ZmdodDNYaTBQNm5CVVU2aW4yaFlPTDQKpyPr20dVzuD9ySDgTydfRAPsI2h8k6F5
            +adNA5HF4ulYKKrDzVO4hWnJ6sC8IKvBa2ZAVkhfoOSOPtqLqFs4hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T09:28:48Z"
    mac: ENC[AES256_GCM,data:l1bZr/dqnktHcmZlmp/kF9Y17I3wA+TpELpbl8/uyjhWEGlKuJCoWSsRAs4/iyVj7OYSkpTd1YorF4n9fsXBGFsKttrZH4fAsEKy+Esk+i/bOzbGn1bRqS1tgFaoPDVpm7sfPpiyewp15PVn0fzqJyEjcnf3MlNB+AifEBHW39k=,iv:CICjKaWmF/3yyl+j3ELrrQEVxiVhXrKPZ/dVv9WNaFM=,tag:HIGBwXi0g4dt1VHkgyFq7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
