apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-andmore2
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: andmore2
        helm.toolkit.fluxcd.io/name: nats-andmore2
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-andmore2-credentials
    namespace: tenant-root
data:
    siempie: ENC[AES256_GCM,data:ITW+0cr4y8pvV/mYbHaf9w==,iv:M/4xBoj5vaTIaVazJfWL7DTcUGHd5P8c8HMtxlGINj8=,tag:ZdWGlmJcfS5MyGJgSiw3HQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ri9Fb25yZ3A4ZHJOeGdQ
            K2NGOEpCdzZpQWo4eDdmL0lVSFdVZ2FWaG5rCjlrb0x5bkJrQlI2RWd4SWpSanlR
            anVPdVdFREowV041SHVhbVh5UUlSOE0KLS0tIERHZmZ1ZGM1WXlTVmF3dkNWcXhp
            TTF3cm82SFhLS0JVNGRHc21DWEdFU0UKuDeIb0d7T2RqrsAkgg/S+OY3NRLhO2Uy
            LdbLOLykGHk/U6rIv0xBkS4v1u5/PYVBP7HUGYcD5y9rXn6+wGgamw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T05:24:23Z"
    mac: ENC[AES256_GCM,data:XYtFDzRY/58HAaN6ibQ67Kq7AT8p+Z9pOut6uwHZtHm/0j11xlW3ovnMLJ0k66o+xPowsO6B6eUmFGGgIRULeRyQV+4wspkTbic+MlmQL1Yfh8QElZ+0f7dJopiqRq6A5QaxS4/jfK2HsdbKTu5+ukSpc8l6tUPqsCmrWX3tYIs=,iv:3ab8eV9nJdN7d39W8MsTLl5q3PKUNYvk6+9wYCQB+WY=,tag:qi/jqr0JPhuu7/Ip6cP3xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
