apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-test123
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: test123
        helm.toolkit.fluxcd.io/name: nats-test123
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-test123-credentials
    namespace: tenant-root
data:
    23sdf: ENC[AES256_GCM,data:anUEPg==,iv:mmvpYG/VenYz66hQWXdgrlWfkpe4xjjoOShrnLGd8Ok=,tag:Asv/eg/qfBNZ3zZ/fIaShg==,type:str]
    s: ENC[AES256_GCM,data:YHG36w==,iv:RPxi3GrmAzUp+7vezF06CTLWFjd3wwsqDlE874m3DLc=,tag:5Ce64bQyVjfmgT845C4S0Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMTI3TlAyajBTVk9BT043
            SjlhWXMxZmlkdFBGRTF3MGdkMDkvdUtLM0VRCnhKN2JKemMrS3ZHY3RqN0NEMEVI
            L1FOYXJFSHNtZ3VFV3Q3akdqYXU2d2MKLS0tIE8vMG1FNisxcFlpZmFTVmoxbFlO
            VjBNcVNZaXRpczRHejlBTXk4c2FkbmcK1VaMCVR+UwkBbXnvH3jjeamf5+JsGLv2
            GxyS/h3KbknS1GxOfdEn1DrN4pRC2X+d5TYTd5ygDNDkRSaYLljE7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T05:24:24Z"
    mac: ENC[AES256_GCM,data:hxGGPJ8mRaE9LTjQpQZWetmV616LVOj6fcwdJRn+TpLo37/sQp0jjzBzTnfwP6TtQcziFvrl5eW0KICLmDG0FFFeFteKn3T3+n8b6Q0cGggerctD7vOoNZ7IViP0pkC+4N6ssHZWqbVT/Zbjku6IcAVEYAzY1cqAFrlTDgEQuRM=,iv:NRAs2naoGY5HeNe0uuhn2TP4tN82O52dA+0Gx5FOvOg=,tag:eTxwfZ56640UKjUs3duUIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
