apiVersion: core.cozystack.io/v1alpha1
kind: TenantSecret
metadata:
    annotations:
        meta.helm.sh/release-name: nats-andmore2
        meta.helm.sh/release-namespace: tenant-root
    labels:
        app.kubernetes.io/managed-by: Helm
        apps.cozystack.io/application.group: apps.cozystack.io
        apps.cozystack.io/application.kind: NATS
        apps.cozystack.io/application.name: andmore2
        helm.toolkit.fluxcd.io/name: nats-andmore2
        helm.toolkit.fluxcd.io/namespace: tenant-root
        internal.cozystack.io/managed-by-cozystack: "true"
    name: nats-andmore2-credentials
    namespace: tenant-root
data:
    siempie: ENC[AES256_GCM,data:ESvLIA4d75lyrU4rr+a7qw==,iv:vbvyMMD1wBnFHeDIrE/LBbAE8SFv3fC5QHjhtXbrSNw=,tag:CIiAQBYAXkAAB2x7uz/iOw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweWR0dWNrZnBvT21nc2Qx
            cCtwQWNLbGY2NkZOK3pHbDhhSHlvQXQvbmxvCmExVlZsS1l3ZG15dzJ6Vy80NWhk
            Uk5IUHJuenZmOENQYXplbEgrL3lXRGMKLS0tIGRTakJZVmlQY2tOb1JtZEdndm1k
            RnZFTkwrQzhHejhBS0J1ZkZjc0h3UjAKjTjpSnkkaUb/WKBehLEELrhL+wuR4D3z
            8dMGy/NqHw/lzrAW+FwPIoRcj0EtZEvGy6AABFcozrG4L9IC77vboQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T16:14:16Z"
    mac: ENC[AES256_GCM,data:9jDU2NpXdeZE2mCdx3OvVGuJSNYuP+47uABH/lbciM6507e1wH7EwDdZeKqTBg0Y0h3VVBgLGbyxGQK/fIwcjQiwDc7ZRBLojAa4Y0/8TGIkr1I4LQvNwajRN8TKMuNOvVwHpvX1PVE/4DGXreVX3/Asbs+bLzObn7NSHNS5ad0=,iv:1hxY0UexxwHDJbHFlAnDXfafouA7FCJq2l9n//qJwAg=,tag:om+DvfMtVg8KdLQ2nReqRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
