apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/package: cozystack.cert-manager
  name: cert-manager-issuers
  namespace: cozy-cert-manager
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-cert-manager-default-cert-manager-issuers
    namespace: cozy-system
  dependsOn:
  - name: cert-manager
    namespace: cozy-cert-manager
  - name: cilium
    namespace: cozy-cilium
  - name: cilium-networkpolicy
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 30s
    timeout: 10m0s
  interval: 5m0s
  maxHistory: 5
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 30s
    timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: cozystack-values
