apiVersion: apps.cozystack.io/v1alpha1
kind: MongoDB
metadata:
  name: simon2
  namespace: tenant-root
spec:
  backup:
    destinationPath: s3://bucket/path/to/folder/
    enabled: false
    endpointURL: http://minio-gateway-service:9000
    retentionPolicy: 30d
    s3AccessKey: ""
    s3SecretKey: ""
    schedule: 0 2 * * *
  bootstrap:
    backupName: ""
    enabled: false
    recoveryTime: ""
  databases:
    hoofd:
      roles:
        admin:
        - simon
        readonly: []
  external: false
  replicas: 3
  resources: {}
  resourcesPreset: t1.small
  sharding: false
  shardingConfig:
    configServerSize: 3Gi
    configServers: 3
    mongos: 2
    shards:
    - name: rs0
      replicas: 3
      size: 10Gi
  size: 10Gi
  storageClass: local
  users:
    simon:
      password: blaaat
  version: v8
