apiVersion: apps.cozystack.io/v1alpha1
kind: NATS
metadata:
  name: simon-first-tenant-nats
  namespace: tenant-simonsfirsttenant
spec:
  config:
    merge: {}
    resolver: {}
  external: false
  jetstream:
    enabled: true
    size: 1Gi
  replicas: 1
  resources: {}
  resourcesPreset: t1.nano
  storageClass: local
  users: {}
