apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozyhr.cozystack.io/values-files: values.yaml,values-talos.yaml,values-kubeovn.yaml
  labels:
    cozystack.io/package: cozystack.networking
    cozystack.io/privileged: "true"
  name: cilium
  namespace: cozy-cilium
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-networking-kubeovn-cilium-cilium
    namespace: cozy-system
  install:
    remediation:
      retries: -1
    timeout: 10m0s
  interval: 5m0s
  upgrade:
    remediation:
      retries: -1
    timeout: 10m0s
  values:
    cilium:
      cgroup:
        autoMount:
          enabled: false
      k8sServiceHost: localhost
      k8sServicePort: "7445"
  valuesFrom:
  - kind: Secret
    name: cozystack-values
