apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/package: cozystack.networking
    cozystack.io/privileged: "true"
  name: cilium-networkpolicy
  namespace: cozy-cilium
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-networking-kubeovn-cilium-cilium-networkpolicy
    namespace: cozy-system
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  install:
    remediation:
      retries: -1
    timeout: 10m0s
  interval: 5m0s
  upgrade:
    remediation:
      retries: -1
    timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: cozystack-values
