apiVersion: v1
kind: Status
metadata:
  name: cilium
  namespace: cozy-cilium
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "cilium":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
