apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: vertical-pod-autoscaler
    meta.helm.sh/release-namespace: cozy-vertical-pod-autoscaler
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
    helm.toolkit.fluxcd.io/name: vertical-pod-autoscaler
    helm.toolkit.fluxcd.io/namespace: cozy-vertical-pod-autoscaler
  name: vpa-for-vpa
  namespace: cozy-vpa-for-vpa
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-vertical-pod-autoscaler-default-vpa-for-vpa
    namespace: cozy-system
  dependsOn:
  - name: monitoring-agents
    namespace: cozy-monitoring
  install:
    crds: Skip
    remediation:
      retries: -1
  interval: 5m
  releaseName: vertical-pod-autoscaler
  upgrade:
    crds: Skip
    remediation:
      retries: -1
  values:
    vertical-pod-autoscaler:
      admissionController:
        enabled: false
      fullnameOverride: vpa-for-vpa
      nameOverride: vpa-for-vpa
      recommender:
        extraArgs:
          recommender-name: vpa-for-vpa
          vpa-object-namespace: cozy-vertical-pod-autoscaler
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
    vpaForVPA: false
