apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/package: cozystack.clickhouse-application
  name: clickhouse-rd
  namespace: cozy-system
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-clickhouse-application-default-clickhouse-rd
    namespace: cozy-system
  dependsOn:
  - name: clickhouse-operator
    namespace: cozy-clickhouse-operator
  install:
    remediation:
      retries: -1
    timeout: 10m0s
  interval: 5m0s
  upgrade:
    remediation:
      retries: -1
    timeout: 10m0s
  valuesFrom:
  - kind: Secret
    name: cozystack-values
