apiVersion: v1
kind: Status
metadata:
  name: cozystack-basics
  namespace: cozy-system
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "cozystack-basics":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
