apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: nats-test123
    meta.helm.sh/release-namespace: tenant-root
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: nats-test123
    helm.toolkit.fluxcd.io/namespace: tenant-root
    sharding.fluxcd.io/key: tenants
  name: nats-test123-system
  namespace: tenant-root
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-nats-application-default-nats-system
    namespace: cozy-system
  install:
    remediation:
      retries: -1
  interval: 5m
  timeout: 10m
  upgrade:
    force: true
    remediation:
      retries: -1
  values:
    nats:
      config:
        cluster:
          enabled: true
          replicas: 2
          routeURLs:
            k8sClusterDomain: cozy.local
        jetstream:
          enabled: true
          fileStore:
            enabled: true
            pvc:
              enabled: true
              size: 1Gi
              storageClassName: local
        monitor:
          enabled: true
      container:
        merge:
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 128Mi
            requests:
              cpu: "0.025"
              ephemeral-storage: "53687091"
              memory: "134217728"
      fullnameOverride: nats-test123
  valuesFrom:
  - kind: Secret
    name: cozystack-values
