apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    apps.cozystack.io-reverse-cozystack.test/audit-nudge: "2026-05-20T22:15:57+02:00"
  labels:
    apps.cozystack.io/application.group: apps.cozystack.io
    apps.cozystack.io/application.kind: Tenant
    apps.cozystack.io/application.name: simonsfirsttenant
    sharding.fluxcd.io/key: tenants
  name: tenant-simonsfirsttenant
  namespace: tenant-root
spec:
  chartRef:
    kind: ExternalArtifact
    name: cozystack-tenant-application-default-tenant
    namespace: cozy-system
  install:
    remediation:
      retries: -1
  interval: 5m0s
  upgrade:
    remediation:
      retries: -1
  values:
    etcd: false
    host: ""
    ingress: false
    monitoring: false
    resourceQuotas: {}
    schedulingClass: ""
    seaweedfs: false
  valuesFrom:
  - kind: Secret
    name: cozystack-values
