apiVersion: apps.cozystack.io/v1alpha1
kind: NATS
metadata:
  name: my-first-again
  namespace: tenant-root
spec:
  config:
    merge: {}
    resolver: {}
  external: false
  jetstream:
    enabled: true
    size: 1Gi
  replicas: 2
  resources: {}
  resourcesPreset: t1.nano
  storageClass: local
  users:
    simon:
      password: simon234
