# .sops.yaml
creation_rules:
  # Encrypt only Kubernetes Secret payloads written as *.sops.yaml files.
  - path_regex: '.*\.sops\.ya?ml$'
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - "age1vrec87smur9jr5m4w8xku9f0av5en0yk7rczqtm54ussw0uu8a8qd58teq"
