apiVersion: core.cozystack.io/v1alpha1
kind: TenantModule
metadata:
  annotations:
    meta.helm.sh/release-name: tenant-root
    meta.helm.sh/release-namespace: tenant-root
  labels:
    app.kubernetes.io/instance: tenant-root
    app.kubernetes.io/managed-by: Helm
    apps.cozystack.io/application.group: apps.cozystack.io
    apps.cozystack.io/application.kind: Info
    apps.cozystack.io/application.name: info
    helm.toolkit.fluxcd.io/name: tenant-root
    helm.toolkit.fluxcd.io/namespace: tenant-root
    sharding.fluxcd.io/key: tenants
  name: info
  namespace: tenant-root  
