apiVersion: v1
kind: Status
metadata:
  name: metrics-server
  namespace: cozy-monitoring
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "metrics-server":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
