apiVersion: v1
kind: Status
metadata:
  name: clickhouse-operator
  namespace: cozy-clickhouse-operator
message: 'Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "clickhouse-operator":
  the object has been modified; please apply your changes to the latest version and
  try again'
reason: Conflict
